title: NEARWEEK
description: Exploring where AI meets crypto
url: https://b4ltasar.github.io
baseurl: ""
# Force rebuild

markdown: kramdown
timezone: Europe/Copenhagen

# Content validation
validate_content: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include API directory for Vercel
include:
  - api
