# Content validation schema
# This helps ensure data consistency across the site
validation:
  cards:
    required: [title, text, image, link]
    properties:
      title: 
        type: string
        minLength: 1
        maxLength: 100
      text:
        type: string
        minLength: 1
        maxLength: 200
      image:
        type: string
        pattern: '^/images/.*'
      link:
        type: string
        pattern: '^https?://.*|^/.*'

  posts:
    required: [title, excerpt, date, author, slug, link]
    properties:
      title:
        type: string
        minLength: 1
        maxLength: 150
      excerpt:
        type: string
        minLength: 1
        maxLength: 300
      date:
        type: string
        pattern: '^\d{4}-\d{2}-\d{2}$'
      author:
        type: string
        minLength: 1
      slug:
        type: string
        pattern: '^[a-z0-9-]+$'
      featured:
        type: boolean
      tags:
        type: array
        items:
          type: string
